### ISSUE TITLE
provide id to image path/file name mapping (id2image.jsonl)

### ISSUE THREAD

**Issue by PaulLerner** [edchengg/oven_eval#1]
Hi,

You did not share the file referenced here
https://github.com/edchengg/oven_eval/blob/e23dde3d08d41e23ed3103abc02ef9bb191279a7/run_blip2_oven.py#L77C19-L77C19

I guess it’s not a huge problem as files are named `<id>.<ext>` where `<ext>` might be JPG and all ids are unique?

**Comment by PaulLerner** [comment]
I think I managed to reconstruct the mapping from the original file names provided (`ovenid2impath.csv`)

**Comment by edchengg** [comment]
That's correct!
