### ISSUE TITLE
How to obtain the annotation files?

### ISSUE THREAD

**Issue by luomancs** [edchengg/oven_eval#3]
Hi, 

Thank you for sharing the dataset, could you share how to exactly download the annotation files? In your instruction, you said run the download script in the image folder, but I could not find the exact script to download the annotation files. I also requested the access to the google drive where you share the images, query and entities, but not the annotation files. 

Thanks,

**Comment by edchengg** [comment]
Hi,

Thanks for your interest!
1. Please use the bash script in the google drive:
`oven_data/download_oven_jsonl.sh`
to download the annotation files.
2. You can find answers for the test and human set inside test_data folder
`test_data/oven_human.jsonl, test_data/oven_query_test.jsonl, test_data/oven_entity_test.jsonl`
3. You can download the image dump and wikipedia dump (w/ images) from the google drive as well.
- oven_images
- all_wikipedia_images.tar

Feel free to let me know if you have any other questions.

**Comment by luomancs** [comment]
Hi, 

I have done step 1 and step 2, but in the step 2, the oven_query_test.jsonl, it does not show answer, I only see data_id, image_id, question, entity_id, entity_text, and data_split. 

Also, does the training set has the answer as well? 

Thanks a lot.

**Comment by edchengg** [comment]
Hi @luomancs,

Please let me clarify the annotation. As OVEN is a visual entity recognition task formulated as a VQA format, the input to the model is (image, question) and the output/answer/target is (`entity_text`). 
For example, "what is the model of the car?" + image --> "Bugatti Veyron".

We also provide `entity_id`, which is the WikiData entity id (unambiguous) of the corresponding entity. This id is used for the final evaluation to calculate accuracy.

- does the training set has the answer as well?
Yes, we released all annotations

**Comment by luomancs** [comment]
Hi there, 

Thank you for your answer. I have one more question regarding to the imagenet image download. I have run the script download_imagenet.sh, however, after it downloaded the images, the unzip folder only contained the imagenet21k_small_classes. However, in the ovenid2impath.csv file, it is looking for imagenet21k_train or imagenet21k_val. How can I resolve such an issue ?

Thank you.

**Comment by edchengg** [comment]
Hi @luomancs,

You can download the image dump of all images used in OVEN from the google drive: `oven_images/shard0{0-5}.tar`.

Thank you.

**Comment by luomancs** [comment]
Hi @edchengg 

Thank you for pointing the shard folder that has been preprocessed. I did aware of these files, which I can easily download locally,  but do you have a recommendation how to download this from a remote server? I have been searching different ways (gdown or wget), unfortunately none of them working for me yet. I really appreciate if you can provide some pointer. 

Thanks a lot.

**Comment by edchengg** [comment]
Hi @luomancs ,

Sorry for the delay and thanks for raising this issue.
I've upload dataset/images to huggingface:

https://huggingface.co/datasets/ychenNLP/oven

You can use wget to download these files easily.
