### ISSUE TITLE
CLIP models

### ISSUE THREAD

**Issue by alejosierra** [edchengg/oven_eval#4]
Hi, thank you for publishing this dataset.

I have a question, is the code for the CLIP experiments (Fusion and CLIP2CLIP), available somewhere?

Cheers.

**Comment by edchengg** [comment]
Hi, you can check out UniIR https://github.com/TIGER-AI-Lab/UniIR
We didn't release CLIP2CLIP version used in oven paper.
The UniIR model should be a well trained model for OVEN

**Comment by alejosierra** [comment]
Thank you
